import type { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/Layout/Footer";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-144x144.png" />
      </Head>
      <div className={styles.container}>
        <Footer />
      </div>
    </>
  );
};

export default Home;
